addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.5.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.5.4")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.17.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.6.4")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.13.0")
